config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  resources :members, only: [:index, :new, :create, :show] do
    resources :search, only: [:index], controller: 'members/search'
    resources :friendships, only: [:create], controller: 'members/friendships'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord

  belongs_to :member
  belongs_to :friend, class_name: 'Member'

  after_create :update_friendship_graph

  private

  def update_friendship_graph
    graph = FriendshipGraph.first
    graph.data[member.id].push(friend.id)
    graph.data[friend.id].push(member.id)
    graph.save
  end

end

app/models/friendship_graph.rb
class FriendshipGraph < ApplicationRecord

  serialize :data, Hash

  def search(from, to)
    return nil unless data[from].present?

    queue = Queue.new
    data[from].each { |id| queue.push([id]) }

    seen = []

    until queue.empty?
      path = queue.pop

      data[path.last].each do |id|
        new_path = path + [id]
        return new_path if id == to

        unless seen.include? id
          seen.push(id)
          queue.push(new_path)
        end
      end
    end

    return nil
  end

end

app/models/member.rb
class Member < ApplicationRecord

  serialize :content, Array

  validates_presence_of :name
  validates_presence_of :url
  validates_presence_of :full_url
  validate :url_is_shortened

  after_create :set_content
  after_create :update_graph

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship',
    foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :member

  def friend_count
    friends.count + inverse_friends.count
  end

  def self.search_for(query, member)
    self.where("content LIKE :query", query: "%#{sanitize_sql_like(query)}%")
      .where.not(id: [member.id] + member.friend_ids )
  end

  def friend_ids
    friends.map {|friend| friend.id } +
      inverse_friends.map {|friend| friend.id }
  end

  private

  def url_is_shortened
    errors.add(:url, 'must be shortened') unless Embiggen::URI(url).shortened?
  end

  def set_content
    document = Nokogiri::HTML.parse(Net::HTTP.get(URI(full_url)))
    puts document.css('h1').children.map {|el| el.content }
    puts document.css('h2').children.map {|el| el.content }
    puts document.css('h3').children.map {|el| el.content }

    update_attribute(:content, [
      document.css('h1').children.map {|el| el.content },
      document.css('h2').children.map {|el| el.content },
      document.css('h3').children.map {|el| el.content }
    ])
  end

  def update_graph
    graph = FriendshipGraph.first
    graph.data[id] = []
    graph.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end

end

app/controllers/members/friendships_controller.rb
class Members::FriendshipsController < ApplicationController

  def create
    @member = Member.find(params[:member_id])
    friend = Member.find_by(id: params[:id])

    if friend
      friendship = Friendship.create(member: @member, friend: friend)

      unless friendship.valid?
        flash[:error] = friendship.errors.full_messages.join(', ')
      end
    else
      flash[:error] = 'Invalid friend id'
    end

    redirect_to member_path(@member)
  end

end

app/controllers/members/search_controller.rb
class Members::SearchController < ApplicationController

  def index
    @current_member = Member.find(params[:member_id])
    @members = Member.search_for(params[:query], @current_member)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def create
    begin
      member = Member.new(create_params)

      unless member.save
        flash[:error] = member.errors.full_messages.join(', ')
        redirect_to new_member_path and return
      end

      redirect_to member_path(member)
    rescue ActionController::ParameterMissing => exception
      flash[:error] = exception.message
      redirect_to new_member_path
    rescue Embiggen::TooManyRedirects => exception
      flash[:error] = 'Shortened URL has too many redirects'
      redirect_to new_member_path
    rescue Embiggen::BadShortenedURI => exception
      flash[:error] = 'The URL is invalid. Please try another shortened url'
      redirect_to new_member_path
    rescue Embiggen::NetworkError => exception
      flash[:error] = 'There was an error processing the URL. Please try again'
      redirect_to new_member_path
    end
  end

  def show
    @member = Member.find(params[:id])
    @h1_contents = @member.content.first
    @h2_contents = @member.content.second
    @h3_contents = @member.content.third
    @friends = @member.friends + @member.inverse_friends
  end

  private

  def create_params
    accepted_params = params.require(:member).permit(:name, :url)
    accepted_params.merge({
      full_url: Embiggen::URI(accepted_params[:url]).expand
    })
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def search_result_connection(member)
    path = FriendshipGraph.first.search(@current_member.id, member.id)
    return 'no mutual friendships' unless path
    path.map {|id| Member.find(id).name }.join(' > ')
  end

  def search_result_match(member)
    member.content.flatten.select {|header| header.downcase.include? params[:query] }
      .join(', ')
  end

end

app/views/index/index.html.erb
<%= link_to 'View all members', members_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h1>All Members</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Friend Count</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.name, member %></td>
          <td><%= member.url %></td>
          <td><%= member.friend_count %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<hr>
<%= link_to 'Create a new member >', new_member_path %>

app/views/members/new.html.erb
Create a new member

<%= form_for @member do |f| %>
  <% if flash[:error] %>
    <div><%= flash[:error] %></div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>
  <%= f.label :url %>
  <%= f.url_field :url, required: true %>
  <%= f.submit %>
<% end %>

app/views/members/search/index.html.erb
<% if @members.empty? %>
  No Results
<% else %>
  <% @members.each do |member| %>
    <%= search_result_connection(member) + " (\"#{search_result_match(member)}\")" %>
  <% end %>
<% end %>

app/views/members/show.html.erb
<h1><%= @member.name %></h1>
<p><%= @member.url %></p>
<p><%= @member.full_url %></p>

<% @h1_contents.each do |h1_content| %>
  <h1><%= h1_content %></h1>
<% end %>

<% @h2_contents.each do |h2_content| %>
  <h2><%= h2_content %></h2>
<% end %>

<% @h3_contents.each do |h3_content| %>
  <h3><%= h3_content %></h3>
<% end %>

<hr>

<h2>Friends</h2>
<%= form_tag member_friendships_path(@member) do %>
  <% if flash[:error] %>
    <div><%= flash[:error] %></div>
  <% end %>
  <%= number_field_tag(:id) %>
  <%= submit_tag 'Add friend' %>
<% end %>
<% @friends.each do |friend| %>
  <%= link_to  friend.name, member_path(friend) %>
<% end %>

<hr>

<h2>Search for experts</h2>
<%= form_tag member_search_index_path(@member), method: 'GET' do %>
  <%= text_field_tag(:query) %>
  <%= submit_tag 'Search' %>
<% end %>